// apps/react/src/pages/Exchange.tsx
/*
 * Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
 */

import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ApiError,
  api,
  type ExchangeDirection,
  type ExchangeDone,
  type ExchangeQuote,
  type ExchangeRequest,
} from '../lib/api.ts';
import { useAsync } from '../lib/hooks.ts';
import { ErrorBox, Loading } from '../components/States.tsx';

const DIRECTIONS: Array<{ id: ExchangeDirection; label: string; hint: string }> = [
  { id: 'in', label: '买入（平台币 → 游戏币）', hint: '花费平台币，得到游戏币' },
  { id: 'out', label: '卖出（游戏币 → 平台币）', hint: '花费游戏币，得到平台币' },
];

export function Exchange() {
  const games = useAsync(() => api.games({ per_page: 100 }), []);
  const [pickedGame, setPickedGame] = useState('');
  const [pickedCurrency, setPickedCurrency] = useState('');
  const [direction, setDirection] = useState<ExchangeDirection>('in');
  const [amount, setAmount] = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [quote, setQuote] = useState<{ req: ExchangeRequest; data: ExchangeQuote } | null>(null);
  const [done, setDone] = useState<ExchangeDone | null>(null);

  const items = games.data?.items ?? [];
  // 未手动选择时回落到第一个游戏/币种，省去 useEffect 同步
  const game = items.find((g) => g.id === pickedGame) ?? items[0] ?? null;
  const currencies = game?.currencies ?? [];
  const currency =
    currencies.find((c) => c.id === pickedCurrency) ?? currencies[0] ?? null;
  const dir = DIRECTIONS.find((d) => d.id === direction) ?? DIRECTIONS[0];

  /** direction='out'（卖）时，后端复用 platform_amount 字段承载「游戏币」数量，勿按字面改名 */
  const buildReq = (): ExchangeRequest => ({
    game_id: game?.id ?? '',
    currency_id: currency?.id ?? '',
    direction,
    platform_amount: amount.trim(),
  });

  // 询价后任何输入变化都会让报价失效，避免按旧价成交
  const fresh =
    quote !== null &&
    quote.req.game_id === (game?.id ?? '') &&
    quote.req.currency_id === (currency?.id ?? '') &&
    quote.req.direction === direction &&
    quote.req.platform_amount === amount.trim();

  // 成交响应的两个金额字段随方向换位（docs/API.md 的 buy/sell）：
  // in 下 platform_amount=支出的平台币、game_amount=到账游戏币；
  // out 下 game_amount=卖出的游戏币、platform_amount=到账平台币。
  // 写死标签 + 写死字段会把 out 的两个数标反。
  const sells = done?.direction === 'out';
  const spentAmount = sells ? done?.game_amount : done?.platform_amount;
  const receivedAmount = sells ? done?.platform_amount : done?.game_amount;

  const doQuote = async () => {
    setErr(null);
    setDone(null);
    setBusy(true);
    try {
      const req = buildReq();
      setQuote({ req, data: await api.exchangeQuote(req) });
    } catch (e) {
      setErr(e instanceof ApiError ? `${e.message}（${e.code}）` : '询价失败，请稍后重试');
    } finally {
      setBusy(false);
    }
  };

  const doExchange = async () => {
    if (!quote) return;
    setErr(null);
    setBusy(true);
    try {
      // 用询价时那份请求下单，保证「看到的价」与「成交的额」一致
      setDone(
        direction === 'in'
          ? await api.exchangeBuy(quote.req)
          : await api.exchangeSell(quote.req),
      );
      setQuote(null);
    } catch (e) {
      setErr(e instanceof ApiError ? `${e.message}（${e.code}）` : '兑换失败，请稍后重试');
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <section className="stack">
        <p className="label">兑换</p>
        <h1 className="h1">
          兑换
          <span style={{ color: 'var(--orange)' }}>.</span>
        </h1>
        <p className="small muted" style={{ margin: 0 }}>
          先询价再确认，{dir.hint}。<Link to="/wallet">返回钱包</Link>
        </p>
      </section>

      <section className="card" aria-label="兑换下单">
        {games.loading && <Loading />}
        {!games.loading && games.error && <ErrorBox message={games.error} onRetry={games.reload} />}
        {!games.loading && !games.error && items.length === 0 && (
          <div className="state">
            <p className="state__k">暂无可兑换的游戏</p>
          </div>
        )}

        {!games.loading && !games.error && items.length > 0 && (
          <form
            className="stack"
            onSubmit={(e) => {
              e.preventDefault();
              void doQuote();
            }}
          >
            {err && (
              <p className="err" role="alert">
                {err}
              </p>
            )}

            <label className="field">
              <span>游戏</span>
              <select
                className="input"
                name="game_id"
                value={game?.id ?? ''}
                onChange={(e) => {
                  setPickedGame(e.target.value);
                  setPickedCurrency('');
                  setQuote(null);
                }}
              >
                {items.map((g) => (
                  <option key={g.id} value={g.id}>
                    {g.name}
                  </option>
                ))}
              </select>
            </label>

            <label className="field">
              <span>游戏币种</span>
              <select
                className="input"
                name="currency_id"
                required
                value={currency?.id ?? ''}
                onChange={(e) => {
                  setPickedCurrency(e.target.value);
                  setQuote(null);
                }}
              >
                {currencies.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}（{c.symbol}）汇率 {c.exchange_rate}
                  </option>
                ))}
              </select>
            </label>

            {currencies.length === 0 && (
              <p className="small muted" style={{ margin: 0 }}>
                该游戏未配置币种，无法兑换。
              </p>
            )}

            <div className="tabs" role="tablist" aria-label="兑换方向">
              {DIRECTIONS.map((d) => (
                <button
                  key={d.id}
                  type="button"
                  role="tab"
                  aria-selected={direction === d.id}
                  className={`tabs__b${direction === d.id ? ' is-on' : ''}`}
                  onClick={() => {
                    setDirection(d.id);
                    setQuote(null);
                  }}
                >
                  {d.id === 'in' ? '买入' : '卖出'}
                </button>
              ))}
            </div>

            <label className="field">
              <span>{direction === 'in' ? '平台币数量' : '游戏币数量'}</span>
              <input
                className="input"
                name="platform_amount"
                type="text"
                inputMode="decimal"
                autoComplete="off"
                required
                value={amount}
                onChange={(e) => {
                  setAmount(e.target.value);
                  setQuote(null);
                }}
              />
            </label>

            <button
              type="submit"
              className="btn btn--block"
              disabled={busy || currencies.length === 0}
            >
              {busy && <span className="spin" aria-hidden="true" />}
              询价
            </button>
          </form>
        )}
      </section>

      {quote && (
        <section className="card" aria-label="询价结果" role="status">
          <p className="label">询价结果</p>
          <div className="list" style={{ marginTop: 12 }}>
            <div className="li">
              <span className="small muted">汇率</span>
              <span className="mono">{quote.data.rate}</span>
            </div>
            <div className="li">
              <span className="small muted">价差</span>
              <span className="mono">{quote.data.spread_pct}%</span>
            </div>
            <div className="li">
              <span className="small muted">价差费用</span>
              <span className="mono">{quote.data.spread_fee}</span>
            </div>
            {'actual_game_amount' in quote.data ? (
              <>
                <div className="li">
                  <span className="small muted">卖出平台币</span>
                  <span className="mono">{quote.data.platform_amount}</span>
                </div>
                <div className="li">
                  <span className="small muted">买入游戏币</span>
                  <span className="mono">{quote.data.game_amount}</span>
                </div>
                <div className="li">
                  <span className="small muted">实际到账游戏币</span>
                  <span className="mono">{quote.data.actual_game_amount}</span>
                </div>
              </>
            ) : (
              <>
                <div className="li">
                  <span className="small muted">卖出游戏币</span>
                  <span className="mono">{quote.data.platform_amount}</span>
                </div>
                <div className="li">
                  <span className="small muted">折算平台币</span>
                  <span className="mono">{quote.data.platform_equivalent}</span>
                </div>
                <div className="li">
                  <span className="small muted">实际到账平台币</span>
                  <span className="mono">{quote.data.actual_platform_amount}</span>
                </div>
              </>
            )}
          </div>

          {fresh ? (
            <button
              type="button"
              className="btn btn--primary btn--block"
              style={{ marginTop: 16 }}
              disabled={busy}
              onClick={() => void doExchange()}
            >
              {busy && <span className="spin" aria-hidden="true" />}
              {direction === 'in' ? '确认买入' : '确认卖出'}
            </button>
          ) : (
            <p className="small muted" style={{ marginBottom: 0, marginTop: 12 }}>
              输入已变更，请重新询价后再确认。
            </p>
          )}
        </section>
      )}

      {done && (
        <section className="card" aria-label="兑换结果" role="status">
          <p className="label">兑换成功</p>
          <div className="list" style={{ marginTop: 12 }}>
            <div className="li">
              <span className="small muted">兑换单号</span>
              <span className="mono">{done.exchange_id}</span>
            </div>
            <div className="li">
              <span className="small muted">方向</span>
              <span className="pill pill--plain">{done.direction === 'in' ? '买入' : '卖出'}</span>
            </div>
            <div className="li">
              <span className="small muted">{sells ? '卖出游戏币' : '支付平台币'}</span>
              <span className="mono">{spentAmount}</span>
            </div>
            <div className="li">
              <span className="small muted">
                {sells ? '到账平台币（已扣点差）' : '到账游戏币（已扣点差）'}
              </span>
              <span className="mono">{receivedAmount}</span>
            </div>
            <div className="li">
              <span className="small muted">价差费用</span>
              <span className="mono">{done.spread_fee}</span>
            </div>
            <div className="li">
              <span className="small muted">成交后平台币余额</span>
              <span className="mono">{done.balance_after}</span>
            </div>
          </div>
        </section>
      )}
    </>
  );
}

// apps/angular/src/app/pages/exchange.ts
/* Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz */
import { Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  Api,
  ApiError,
  ExchangeDirection,
  ExchangeDone,
  ExchangePayload,
  ExchangeQuote,
  Game,
  money,
} from '../core/api.service';

/** 游戏列表单页条数；超过再加“加载更多”（复用 gameList 的 page 参数） */
const GAMES_PER_PAGE = 100;

/** 兑换：选游戏 → 选该游戏币种 → 买/卖 → 询价 → 确认。
 *  game_id / currency_id 均为服务端下发的 hashid，不能自行拼造。 */
@Component({
  selector: 'app-exchange',
  imports: [RouterLink],
  template: `
    <div class="stack">
      <a class="btn ghost back" routerLink="/wallet">← 返回钱包</a>

      @if (done(); as d) {
        <div class="card stack">
          <div class="between">
            <span class="label">兑换完成</span>
            <span class="badge on">{{ d.direction === 'in' ? '买入' : '卖出' }}</span>
          </div>
          <div class="kv">
            <span class="muted">{{ d.direction === 'in' ? '支付平台币' : '卖出游戏币' }}</span>
            <span class="mono">{{
              d.direction === 'in' ? d.platform_amount : d.game_amount
            }}</span>
          </div>
          <div class="kv">
            <span class="muted">
              {{ d.direction === 'in' ? '到账游戏币（已扣点差）' : '到账平台币（已扣点差）' }}
            </span>
            <span class="mono amount in">{{
              d.direction === 'in' ? d.game_amount : d.platform_amount
            }}</span>
          </div>
          <div class="kv">
            <span class="muted">点差费用</span><span class="mono">{{ d.spread_fee }}</span>
          </div>
          <div class="kv">
            <span class="muted">成交汇率</span><span class="mono">{{ d.rate }}</span>
          </div>
          <div class="kv">
            <span class="muted">账户余额</span
            ><span class="mono">{{ money(d.balance_after) }}</span>
          </div>
          <div class="wrap">
            <a class="btn" routerLink="/wallet">返回钱包</a>
            <button class="btn ghost" type="button" (click)="again()">再兑一笔</button>
          </div>
        </div>
      } @else {
        <div class="card form">
          <div>
            <span class="label">兑换</span>
            <h1>平台币 / 游戏币互兑</h1>
          </div>

          <label class="field">
            <span>游戏</span>
            <select
              class="input"
              [disabled]="gamesBusy() || !games().length"
              (change)="pickGame($any($event.target).value)"
            >
              @if (!games().length) {
                <option value="">{{ gamesBusy() ? '加载中…' : '暂无可兑换的游戏' }}</option>
              }
              @for (g of games(); track g.id) {
                <option [value]="g.id" [selected]="g.id === gameId()">{{ g.name }}</option>
              }
            </select>
          </label>

          <label class="field">
            <span>游戏币种</span>
            <select
              class="input"
              [disabled]="!currencies().length"
              (change)="pickCurrency($any($event.target).value)"
            >
              @if (!currencies().length) {
                <option value="">该游戏暂无可用币种</option>
              }
              @for (c of currencies(); track c.id) {
                <option [value]="c.id" [selected]="c.id === currencyId()">
                  {{ c.name }}（{{ c.symbol }}）· 汇率 {{ c.exchange_rate }}
                </option>
              }
            </select>
          </label>

          <div class="field">
            <span>方向</span>
            <div class="chips">
              <button
                type="button"
                class="chip"
                [class.on]="direction() === 'in'"
                (click)="pickDirection('in')"
              >
                买入（平台币 → 游戏币）
              </button>
              <button
                type="button"
                class="chip"
                [class.on]="direction() === 'out'"
                (click)="pickDirection('out')"
              >
                卖出（游戏币 → 平台币）
              </button>
            </div>
          </div>

          <label class="field">
            <span>
              @if (direction() === 'in') {
                支付平台币数量
              } @else {
                卖出游戏币数量（{{ cur()?.name || '—' }}）
              }
            </span>
            <input
              class="input mono"
              inputmode="decimal"
              autocomplete="off"
              placeholder="0.00"
              [value]="amount()"
              (input)="onAmount($event)"
            />
            @if (amountError()) {
              <span class="err">{{ amountError() }}</span>
            }
            @if (direction() === 'out') {
              <span class="muted hint">此处填写的是游戏币数量，不是平台币数量。</span>
            }
          </label>

          @if (gamesError()) {
            <div class="alert">
              {{ gamesError() }}
              <button class="btn ghost" type="button" (click)="loadGames()">重试</button>
            </div>
          }
          @if (!quote() && error()) {
            <div class="alert">{{ error() }}</div>
          }

          <button
            class="btn primary wide"
            type="button"
            [disabled]="quoteBusy() || !currencyId()"
            (click)="quoteNow()"
          >
            {{ quoteBusy() ? '询价中…' : '询价' }}
          </button>
        </div>

        @if (quote(); as q) {
          <div class="card stack">
            <span class="label">询价结果</span>
            <div class="kv">
              <span class="muted">汇率</span>
              <span class="mono">1 平台币 ≈ {{ q.rate }} {{ cur()?.name || '' }}</span>
            </div>
            <div class="kv">
              <span class="muted">点差</span><span class="mono">{{ q.spread_pct }}%</span>
            </div>
            <div class="kv">
              <span class="muted">点差费用</span><span class="mono">{{ q.spread_fee }}</span>
            </div>
            @if (direction() === 'in') {
              <div class="kv">
                <span class="muted">折合游戏币（扣点差前）</span
                ><span class="mono">{{ q.game_amount }}</span>
              </div>
              <div class="kv">
                <span class="muted">预计获得</span>
                <span class="mono amount in"
                  >{{ q.actual_game_amount }} {{ cur()?.symbol || '' }}</span
                >
              </div>
            } @else {
              <div class="kv">
                <span class="muted">折合平台币（扣点差前）</span>
                <span class="mono">{{ q.platform_equivalent }}</span>
              </div>
              <div class="kv">
                <span class="muted">预计到账</span>
                <span class="mono amount in">{{ q.actual_platform_amount }} 平台币</span>
              </div>
            }
            @if (error()) {
              <div class="alert">{{ error() }}</div>
            }
            <button class="btn primary wide" type="button" [disabled]="busy()" (click)="confirm()">
              {{ busy() ? '兑换中…' : '确认兑换' }}
            </button>
            <p class="muted hint">报价随行情变动，修改数量或币种后需重新询价。</p>
          </div>
        }
      }
    </div>
  `,
  styles: [
    `
      .back {
        margin-bottom: 0;
        font-size: 13px;
      }
      .form {
        display: flex;
        flex-direction: column;
        gap: 16px;
        padding: 22px 24px 24px;
      }
      .form h1 {
        margin-top: 6px;
      }
      .hint {
        font-size: 12px;
      }
    `,
  ],
})
export class ExchangePage {
  private readonly api = inject(Api);

  protected readonly money = money;

  protected readonly games = signal<Game[]>([]);
  protected readonly gamesBusy = signal(true);
  protected readonly gamesError = signal('');
  protected readonly gameId = signal('');
  protected readonly currencyId = signal('');
  protected readonly direction = signal<ExchangeDirection>('in');
  protected readonly amount = signal('');
  protected readonly amountError = signal('');
  protected readonly error = signal('');
  protected readonly quoteBusy = signal(false);
  protected readonly quote = signal<ExchangeQuote | null>(null);
  protected readonly busy = signal(false);
  protected readonly done = signal<ExchangeDone | null>(null);

  protected readonly currencies = computed(
    () => this.games().find((g) => g.id === this.gameId())?.currencies ?? [],
  );

  protected readonly cur = computed(
    () => this.currencies().find((c) => c.id === this.currencyId()) ?? null,
  );

  constructor() {
    this.loadGames();
  }

  protected loadGames(): void {
    this.gamesBusy.set(true);
    this.gamesError.set('');
    this.api.gameList({ page: 1, per_page: GAMES_PER_PAGE }).subscribe({
      next: (r) => {
        const list = r.items ?? [];
        this.games.set(list);
        this.gamesBusy.set(false);
        if (!this.gameId()) this.pickGame(list[0]?.id ?? '');
      },
      error: (e: ApiError) => {
        this.gamesError.set(e.message);
        this.gamesBusy.set(false);
      },
    });
  }

  protected pickGame(id: string): void {
    this.gameId.set(id);
    this.currencyId.set(this.games().find((g) => g.id === id)?.currencies[0]?.id ?? '');
    this.stale();
  }

  protected pickCurrency(id: string): void {
    this.currencyId.set(id);
    this.stale();
  }

  protected pickDirection(d: ExchangeDirection): void {
    if (this.direction() === d) return;
    this.direction.set(d);
    this.stale();
  }

  protected onAmount(ev: Event): void {
    this.amount.set((ev.target as HTMLInputElement).value);
    this.amountError.set('');
    this.stale();
  }

  /** 询价 */
  protected quoteNow(): void {
    const amount = this.amount().trim();
    if (!amount) {
      this.amountError.set('请输入兑换数量');
      return;
    }
    if (!/^\d+(\.\d+)?$/.test(amount)) {
      this.amountError.set('数量格式不正确，请输入数字');
      return;
    }
    if (!this.gameId() || !this.currencyId()) {
      this.error.set('请先选择游戏与币种');
      return;
    }

    this.quoteBusy.set(true);
    this.error.set('');
    this.api.quoteExchange(this.payload(amount)).subscribe({
      next: (q) => {
        this.quoteBusy.set(false);
        this.quote.set(q);
      },
      error: (e: ApiError) => {
        this.quoteBusy.set(false);
        this.error.set(e.message);
      },
    });
  }

  protected confirm(): void {
    const amount = this.amount().trim();
    if (!this.quote() || !amount) return;

    this.busy.set(true);
    this.error.set('');
    const payload = this.payload(amount);
    const call =
      this.direction() === 'in' ? this.api.exchangeBuy(payload) : this.api.exchangeSell(payload);
    call.subscribe({
      next: (d) => {
        this.busy.set(false);
        this.done.set(d);
        this.quote.set(null);
        this.amount.set('');
      },
      error: (e: ApiError) => {
        this.busy.set(false);
        this.error.set(e.message);
      },
    });
  }

  /** 数量变化后旧报价作废：不允许拿过期价格确认 */
  private stale(): void {
    this.quote.set(null);
    this.error.set('');
  }

  /**
   * 请求体：direction='out'（卖出）时 platform_amount 承载的是【游戏币】数量 ——
   * 服务端复用了同一字段名，不要改成 game_amount。
   */
  private payload(amount: string): ExchangePayload {
    return {
      game_id: this.gameId(),
      currency_id: this.currencyId(),
      direction: this.direction(),
      platform_amount: amount,
    };
  }

  protected again(): void {
    this.done.set(null);
    this.amount.set('');
    this.amountError.set('');
    this.error.set('');
    this.quote.set(null);
  }
}
